services:
  derper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: derper
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./tailscale:/var/lib/tailscale
      - ./derper:/var/lib/derper
    ports:
      - "127.0.0.1:12345:12345"
      - "12346:12346/udp"
    devices:
      - /dev/net/tun:/dev/net/tun
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
